# Generated by Django 4.1.5 on 2023-03-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='A_cover',
            field=models.ImageField(default='Song_cover/default.jpg', upload_to='Song_covers/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover',
            field=models.ImageField(default='Song_cover/default.jpg', upload_to='Song_covers/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(upload_to='songs/'),
        ),
    ]
